[package]
name = "net-ifnames-prefix"
version = "0.1.0"
authors = ["Michal Sekletar <msekleta@redhat.com>"]

[dependencies]
libudev = "0.2"
regex = "1.0.1"
hwaddr = "0.1.4"
rust-ini = "0.12.2"
libc = "0.2.40"
log = "0.4.3"
env_logger = "0.5.10"
